/**
 * Report Formatter
 *
 * Pure Markdown assembly — takes the generated questions and metadata and
 * returns the final report string. No side effects, no I/O.
 */

import { GIT_SHA_SHORT_LENGTH } from './constants.js';

/**
 * Assembles the full Markdown assessment report.
 */
export function formatReport({
  questions,
  files,
  baseSha,
  headSha,
  truncated,
  provider,
  model,
  branchName,
  assignmentContextFiles,
}) {
  const date = new Date().toISOString().replace('T', ' ').substring(0, 19) + ' UTC';
  const shortBase = baseSha.substring(0, GIT_SHA_SHORT_LENGTH);
  const shortHead = headSha.substring(0, GIT_SHA_SHORT_LENGTH);
  const fileList = files.map((f) => `\`${f}\``).join(', ');
  const truncNote = truncated
    ? '> **⚠️ Note:** The content was truncated — questions may not cover all changes.\n'
    : '';

  const isDefaultBranch = !branchName || branchName === 'main' || branchName === 'master';
  const branchNote = isDefaultBranch ? '' : `> **Branch:** \`${branchName}\`\n`;

  const contextNote =
    assignmentContextFiles && assignmentContextFiles.length > 0
      ? `> **Assignment Context:** ${assignmentContextFiles.map((f) => `\`${f}\``).join(', ')}\n`
      : '';

  return [
    '## Grill My Code',
    '',
    `> **Generated:** ${date}`,
    `> **Commits reviewed:** \`${shortBase}\` → \`${shortHead}\``,
    branchNote,
    `> **Code Files Assessed:** ${fileList}`,
    contextNote,
    truncNote,
    '---',
    '',
    questions,
    '',
    '---',
    '',
    `<sub>Generated by [grill-my-code](https://github.com/NSCC-ITC-Assessment/GrillMyCode) · ${model} via ${provider}${process.env.GITHUB_ACTION_REF ? ` · ${process.env.GITHUB_ACTION_REF}` : ''}</sub>`,
  ].join('\n');
}
